// import 'bootstrap/scss/bootstrap-reboot.scss';
// import 'bootstrap/scss/bootstrap.scss';
// import 'bxslider/dist/jquery.bxslider.min.css';
// import 'slick-carousel';
// import 'slick-carousel/slick/slick.scss';
// require('bxslider');
// require('webpack-jquery-ui');
// require('webpack-jquery-ui/css');
require('./scss/index.scss');
require('./js/index.js');